server:
  port: ${PORT:5000}

jwt:
  secret: request-api-http
  expiration: 60000000
  refreshExpirationDateInMs: 9000000

nasa:
  api:
    url: https://api.nasa.gov/neo/rest/v1
    key: IoXbCTZeb4J8ZMAIt5NQKBiBF7jJc4PcvO8HCF63

spring:
  datasource:
    url: jdbc:mysql://mysql21-farm2.uni5.net/rhfactor08?useSSL=false&createDatabaseIfNotExist=true
    username: rhfactor08
    password: AZs4buJS6F
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    tomcat:
      testOnBorrow: true
      validationQuery: SELECT 1
